### ISSUE TITLE
Errors in CodeSandbox for CRA with reshadow/macro

### ISSUE THREAD

**Issue by comerc** [lttb/reshadow#39]
[![Edit frosty-varahamihira-hbo4f](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-varahamihira-hbo4f?fontsize=14)

if new project:
`reshadow/macro: require(...) is not a function`

if shared project:
`reshadow/macro: Error: ENOENT: No such file or directory., '/empty.js'`

**Comment by antonk52** [comment]
Thank you for this and other issues. I will do my best to go over them, but it will probably be over the weekend.

**Comment by lttb** [comment]
Hi @comerc, thank you for the issue.

There is known problem on the Codesandbox with `postcss` on the babel transpiling.
So there are two things to do to get it work with `reshadow/babel` or `reshadow/macro`:

1) create empty file `empty.js` in the root folder
2) add `util` as the dependency (because it is also required by some postcss plugins)

We've made some Codesanbox starters, that you can fork to play around with `reshadow`:
- CRA (`reshadow/macro`): https://codesandbox.io/s/reshadowcra-9o9nq388wp
- React with `reshadow/babel`: https://codesandbox.io/s/reshadowreact-llm3vo07w9

Just to note, you can also use `reshadow` on the Codesandbox without babel and macro, just the runtime version

**Comment by comerc** [comment]
Thanks!

**Comment by comerc** [comment]
@lttb CRA is work with reshadow@0.0.1-alpha.26, but it is not work with reshadow@0.0.1-alpha.65.
